# src/main/resources/application.yml
spring:
  datasource:
    url: "jdbc:mysql://217.154.85.170:3306/spade"
    username: "spade2"
    password: "X5a13ST1UW3lEuk452bg"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: supErsEcrEtKeyforPokerApp12345
    expirationMs: 86400000  # 24 hours