# spadeboot/docker-compose.yml
services:
  app:
    container_name: spadeboot-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: spadeboot-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=v0eJtpsCwHJGq5C4509p
      - MYSQL_DATABASE=SpadeDB
      - MYSQL_USER=spade
      - MYSQL_PASSWORD=v0eJtpsCwHJGq5C4509p
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pv0eJtpsCwHJGq5C4509p"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data: