# spadeboot/docker-compose.yml
services:
  app:
    container_name: spadeboot-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GRB_LICENSE_FILE=/opt/gurobi/licenses/gurobi.lic
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/gurobi.lic:/opt/gurobi/licenses/gurobi.lic:ro
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: spadeboot-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data: